import type { Metadata } from "next";
import { draftMode } from "next/headers";

import "@/styles/globals.css";
import { FooterDocument, SiteLocale, MenuDocument } from "@/graphql/generated";
import HeaderRenderer from "@/components/Header/HeaderRenderer";
import Footer from "@/components/Footer";
import fetchDato from "@/lib/fetchDato";
import MyFooter from "@/components/MyFooter";
import MyHeader from "@/components/MyHeader";

const locale = "it";
const siteLocale = locale as SiteLocale;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isEnabled } = draftMode();

  const footerData = await fetchDato(
    FooterDocument,
    { locale: siteLocale, fallbackLocale: siteLocale },
    isEnabled
  );
  const menuData = await fetchDato(
    MenuDocument,
    {
      locale: siteLocale,
      fallbackLocale: [siteLocale],
    },
    isEnabled
  );

  return (
    <html lang={locale} data-theme="light">
      <body>
        <MyHeader />
        <div className="relative">
          <HeaderRenderer
            data={menuData}
            locale={siteLocale}
            isDraft={isEnabled}
          />
        </div>
        <main className="md:min-h-screen">{children}</main>
        <Footer data={footerData} locale={siteLocale} />
        <MyFooter />
      </body>
    </html>
  );
}
