<<<<<<< HEAD
import { draftMode } from "next/headers";
import { toNextMetadata } from "react-datocms";
import config from "@/data/config";
import "@/styles/globals.css";
import {
  FooterDocument,
  SiteLocale,
  MenuDocument,
  LayoutDocument,
} from "@/graphql/generated";
import HeaderRenderer from "@/components/Header/HeaderRenderer";
import Footer from "@/components/Footer";
import fetchDato from "@/lib/fetchDato";
import myFont from "@/lib/loadCustomFont";

const locale = "en";
const siteLocale = locale as SiteLocale;
const defaultLocale = config.defaultLocale as SiteLocale;

export async function generateMetadata() {
  const siteLocale = locale as SiteLocale;
  const data = await fetchDato(LayoutDocument, { locale: siteLocale }, false);
  const globalSeo = data?._site?.globalSeo || null;
  const fallbackSeo = globalSeo?.fallbackSeo;
  const icon = toNextMetadata(data._site.faviconMetaTags);
  const metaObject = {
    ...icon,
    title: fallbackSeo?.title,
    description: fallbackSeo?.description,
    openGraph: {
      title: fallbackSeo?.title,
      description: fallbackSeo?.description,
      siteName: globalSeo?.siteName,
      images: fallbackSeo?.image,
      locale,
      type: "website",
    },
  };
  return metaObject;
}
=======
import type { Metadata } from "next";
import { draftMode } from "next/headers";

import "@/styles/globals.css";
import { FooterDocument, SiteLocale, MenuDocument } from "@/graphql/generated";
import HeaderRenderer from "@/components/Header/HeaderRenderer";
import Footer from "@/components/Footer";
import fetchDato from "@/lib/fetchDato";
import MyFooter from "@/components/MyFooter";
import MyHeader from "@/components/MyHeader";

const locale = 'en';
const siteLocale = locale as SiteLocale;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> facc883 (wip algolia)

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isEnabled } = draftMode();

  const footerData = await fetchDato(
    FooterDocument,
<<<<<<< HEAD
    { locale: siteLocale, fallbackLocale: [defaultLocale] },
=======
    { locale: siteLocale, fallbackLocale: siteLocale },
>>>>>>> facc883 (wip algolia)
    isEnabled
  );
  const menuData = await fetchDato(
    MenuDocument,
    {
      locale: siteLocale,
<<<<<<< HEAD
      fallbackLocale: [defaultLocale],
=======
      fallbackLocale: [siteLocale],
>>>>>>> facc883 (wip algolia)
    },
    isEnabled
  );

  return (
    <html lang={locale} data-theme="custom">
      <body>
<<<<<<< HEAD
        <HeaderRenderer
          data={menuData}
          locale={siteLocale}
          isDraft={isEnabled}
        />
        <main className={`md:min-h-screen ${myFont.variable}`}>{children}</main>
        <Footer data={footerData} locale={siteLocale} />
=======
        <div className="relative">
          <HeaderRenderer
            data={menuData}
            locale={siteLocale}
            isDraft={isEnabled}
          />
        </div>
        <main className="md:min-h-screen container mx-auto">{children}</main>
        <Footer data={footerData} locale={siteLocale} />
        <MyFooter />
        <MyHeader />
>>>>>>> facc883 (wip algolia)
      </body>
    </html>
  );
}
