import "@/styles/globals.css";
import type { Metadata } from "next";
import { draftMode } from "next/headers";
import MyHeader from "@/components/MyHeader";
import MyFooter from "@/components/MyFooter";

const locale = "it";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={locale} data-theme="dracula">
      <body>
        <MyHeader />
        <main className="md:min-h-screen">{children}</main>
        <MyFooter />
      </body>
    </html>
  );
}
