import "@/styles/globals.css";
import type { Metadata } from "next";
import { draftMode } from "next/headers";
import { SiteLocale } from "@/graphql/generated";
import HeaderRenderer from "@/components/Header/HeaderRenderer";
import Footer from "@/components/Footer";

const locale = "it";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isEnabled } = draftMode();
  return (
    <html lang={locale} data-theme="light">
      <body>
        <HeaderRenderer lng={locale as SiteLocale} isDraft={isEnabled} />
        <main className="md:min-h-screen">{children}</main>
        <Footer lng={locale as SiteLocale} />
      </body>
    </html>
  );
}
