fragment elementsListRecord on ElementsListRecord {
  id
  _modelApiKey
  itemsPrefix
  itemsTitle
  itemsText
  elements {
    ... on PostRecord {
      id
      _modelApiKey
      slug
      abstract
      title
      tags {
        id
        tag
        slug
        _modelApiKey
      }
      blogImage {
        responsiveImage(
          sizes: "(min-width:768px) 50vw, (min-width:1024px) 33vw, 100vw, 500px"
          imgixParams: { auto: [format, compress], fit: crop, ar: "7:8" }
        ) {
          ...rImage
        }
      }
    }
    ... on ProductRecord {
      id
      _modelApiKey
      abstract
      title
      productImage {
        responsiveImage(
          sizes: "(min-width:768px) 50vw, (min-width:1024px) 33vw, 100vw, 500px"
          imgixParams: { auto: [format, compress], fit: crop, ar: "7:8" }
        ) {
          ...rImage
        }
      }
    }
  }
}
