query Footer($locale: SiteLocale, $fallbackLocale: [SiteLocale!]) {
  layout(locale: $locale, fallbackLocales: $fallbackLocale) {
    footerSubtitle
    address
    colorReverseBanner
    email
    facebookPixelId
    footerSubtitle
    googleAnalyticsId
    googleTagManagerId
    id
    iubendaPolicyId
    iubendaSiteId
    iva
    phone
    rea
    theme
    titleNewsletter
    textNewsletter
    urlNewsletter
    googleMaps
    footerLogo {
      url
      height
      width
    }
    socialMediaLinks {
      url
      name
      id
      icon {
        url
        height
        width
      }
    }
    footerLinks {
      _modelApiKey
      id
      slug
      slugs: _allSlugLocales {
        locale
        value
      }
      label
    }
  }
}
