query Footer($locale: SiteLocale, $fallbackLocale: [SiteLocale!]) {
  layout(locale: $locale, fallbackLocales: $fallbackLocale) {
    footerSubtitle
    address
    colorReverseBanner
    email
    facebookPixelId
    footerSubtitle
    googleAnalyticsId
    googleTagManagerId
    id
    iubendaPolicyId
    iubendaSiteId
    iva
    phone
    rea
    titleNewsletter
    textNewsletter
    urlNewsletter
    googleMaps
    footerLogo {
      url
      height
      width
    }
    socialMediaLinks {
      url
      name
      id
      icon {
        url
        height
        width
      }
    }
    footerMenu {
      ... on ColumnsMenuFooterRecord {
        id
        _modelApiKey
        __typename
        label
        page {
          __typename
          ... on PageRecord {
            id
            _modelApiKey
            label
            slug
            slugs: _allSlugLocales {
              locale
              value
            }
          }
          ... on ExternalLinkRecord {
            ...externalLink
          }
        }
      }
      ... on ColumnsTextFooterRecord {
        id
        _modelApiKey
        label
        content {
          value
          blocks {
            id
            _modelApiKey
            __typename
            link {
              ... on InternalLinkRecord {
                ...internalLink
              }
              ... on ExternalLinkRecord {
                ...externalLink
              }
            }
          }
        }
      }
    }
  }
}
