query Tag($locale: SiteLocale, $fallbackLocale: [SiteLocale!], $slug: String) {
  tag(
    filter: { slug: { eq: $slug } }
    locale: $locale
    fallbackLocales: $fallbackLocale
  ) {
    id
    tag
    _modelApiKey
    slugs: _allSlugLocales {
      locale
      value
    }
    seo: _seoMetaTags {
      ...seoMetaFragment
    }
    hero {
      ...heroFragment
    }
    sections {
      ... on SectionWrapRecord {
        id
        label
        _modelApiKey
        title
        style
        blocks {
          ...wrapSectionBlocks
        }
      }
    }
    posts: _allReferencingPosts(
      filter: { title: { isBlank: "false" } }
      orderBy: _createdAt_DESC
      first: "100"
      locale: $locale
    ) {
      _publishedAt
      slug
      id
      title
      tags {
        tag
      }
      blogImage {
        responsiveImage(
          sizes: "(min-width:768px) 50vw, (min-width:1024px) 33vw, 100vw, 500px"
          imgixParams: { auto: [format, compress], fit: crop, ar: "7:8" }
        ) {
          ...rImage
        }
      }
      blogImageHover {
        responsiveImage(
          sizes: "(min-width:768px) 50vw, (min-width:1024px) 33vw, 100vw, 500px"
          imgixParams: { auto: [format, compress], fit: crop, ar: "7:8" }
        ) {
          ...rImage
        }
      }
    }
    _allReferencingPostsMeta(
      locale: $locale
      filter: { title: { isBlank: "false" } }
    ) {
      count
    }
  }
}
